### ISSUE TITLE
[1.16] Makes JEI invalid.

### ISSUE THREAD

**Issue by wasdspace** [Octo-Studios/nerb#1]
As the title. Probably not intended.

**Comment by SSKirillSS** [comment]
Hi! Thanks for your report! Try with the newest version of NERB, it should be fixed now: [\*click\*](https://www.curseforge.com/minecraft/mc-mods/notenoughrecipebook/files/4205708)

**Comment by wasdspace** [comment]
It works! Thanks for your quick fix!
