### ISSUE TITLE
[BUG] hiding Curios slots toggles recipe book and DISABLED issues

### ISSUE THREAD

**Issue by schindlershadow** [Octo-Studios/nerb#15]
1. with `buttonMode: TOGGLE` clicks on the button to hide a curios slot toggles JEI instead

2. also I keep setting `buttonMode: DISABLED` but it randomly gets reset back to TOGGLE

3. DISABLED also does not seem to be working and acts like ENABLED

mc 1.21.1

**Comment by SSKirillSS** [comment]
Which version of NERB and Curios API Continuation do you have installed?

**Comment by schindlershadow** [comment]
Curios API Continuation 9.0.10+1.21
NERB 0.4.1

**Comment by SSKirillSS** [comment]
Try to update your Curios API Continuation to the latest

**Comment by schindlershadow** [comment]
updating to curios-neoforge-9.0.11+1.21 fixed these issues
