### ISSUE TITLE
New version doesn't hide book

### ISSUE THREAD

**Issue by om3ga6400** [Octo-Studios/nerb#18]
![{57EA1146-E6EA-4C13-B894-B07F341E73B7}](https://github.com/user-attachments/assets/361edb0e-9370-4a97-8a71-e7e31f011e85)

**Comment by SSKirillSS** [comment]
![image](https://github.com/user-attachments/assets/05fbb7c9-217b-41f6-8d31-ed11eb699729)

**Comment by om3ga6400** [comment]
how do i change this to just remove it
