### ISSUE TITLE
[Suggestion] Config to retain the recipe book icon

### ISSUE THREAD

**Issue by cntrik** [Octo-Studios/nerb#5]
I utilize EMI and clicking the recipe book switches to craftable items

The craftables still show up with your mod installed, currently using your mod for added optimization so thank you!
![image](https://github.com/SSKirillSS/nerb/assets/11052983/ab0f6f07-ab62-48c1-832b-053f121a378c)

![image](https://github.com/SSKirillSS/nerb/assets/11052983/a4fe23b3-751b-4a1b-bde9-28bea49d8ed9)

**Comment by SSKirillSS** [comment]
Hi. This option was just added to NERB on 1.21 (release will be on CF and Modrinth in a few days). Will be backported to previous versions too when the Config API will be more polished.
